---

# Install jenv

- name: brew install jEnv
  homebrew:
    name: jenv
    state: present

- name: Generate script to profile.d
  become: true
  template:
    src: patch.j2
    dest: /Users/{{ param_user }}/profile.d/jenv.sh
    owner: "{{ param_user }}"
    mode: "0755"

- name: jEnv add Java 8  # noqa 306 Shells that use pipes should set the pipefail option
  shell: . /Users/{{ param_user }}/.bashrc && (yes | jenv add {{ detect_java_8_home.stdout }})
  register: result

- name: jEnv add Java 11  # noqa 306 Shells that use pipes should set the pipefail option
  shell: . /Users/{{ param_user }}/.bashrc && (yes | jenv add {{ detect_java_11_home.stdout }})

- name: Display jEnv home
  debug:
    msg: "{{ result.stdout }}"

- name: set Java 11 as Global in jEnv
  shell: bash -l -c "jenv global 11"

...
