---

# Install jenv

- name: brew install jEnv
  homebrew:
    name: jenv
    state: present

- name: Generate script to profile.d
  become: true
  template:
    src: patch.j2
    dest: /Users/{{ param_user }}/profile.d/jenv.sh
    owner: "{{ param_user }}"
    mode: "0755"

- name: Get available JDKs
  shell: bash -lc 'ls /Library/Java/JavaVirtualMachines/'
  register: jdks
  ignore_errors: true
  changed_when: false

- name: Ensure JDKs are registered
  shell: bash -lc "jenv add /Library/Java/JavaVirtualMachines/{{ item }}/Contents/Home"
  with_items: '{{ jdks.stdout_lines }}'
  ignore_errors: true
  register: result
  changed_when: "'already' not in result.stdout"
  failed_when: "result.rc != 0 and 'already' not in result.stdout"

- name: set Java 11 as Global in jEnv on Xcode stacks
  shell: bash -l -c "jenv global 11"
  when: not is_xamarin|bool

- name: set Java 8 as Global in jEnv on Vs4mac stacks
  shell: bash -l -c "jenv global 1.8"
  when: is_xamarin|bool

- name: Ensure shims are updated
  shell: bash -lc 'jenv rehash'  # noqa no-changed-when

- name: JAVA_HOME is exposed automatically
  shell: bash -lc 'jenv enable-plugin export'  # noqa no-changed-when

...
