---
- name: "Set up wix/brew"
  homebrew_tap:
    name: wix/brew
    state: present

- name: brew install formulas
  homebrew:
    name: "{{ item.name }}"
    state: present
    update_homebrew: true
  with_items:
    - "{{ brew_packages }}"

- name: brew install formulas with version constraints
  homebrew:
    name: "{{ item.name }}"
    state: present
    update_homebrew: true
  with_items:
    - "{{ brew_packages_with_version_constraints }}"
  when: ansible_distribution_version.split(".")[0] | int >= item.minimum_os_version

- name: Install danger-swift below 11.4.x
  homebrew:
    name: "danger/tap/danger-swift"
    state: present
    update_homebrew: false
  when: xcode_version not in danger_swift_unsupported_versions
