---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  become_method: sudo
  any_errors_fatal: true
  vars:
    param_user: vagrant
    param_group: staff
    password_of_param_user: vagrant
  roles:
    - role: python
    - role: certs
#    - role: keychain
    - role: enable-auto-login
    - role: go
    - role: bitrise-specific-folders
    - role: bitrise-cli
    - role: bitrise-agent
    - role: remote-access
#    - role: ssh-setup
    - role: brew-packages
    - role: git
    - role: ruby-gems
    - role: xcode-tools
    - role: brew-cleanup-weekly
