---
- name: Install gem packages
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: "{{ ansible_env.HOME }}/.asdf/shims/gem"
    user_install: false
  with_items:
    - "{{ gem_packages }}"

# GEMs: Cocoapods

- name: Check if cocoapods Specs repo is checked out
  git:
    repo: 'https://github.com/CocoaPods/Specs.git'
    dest: ~/.cocoapods/repos/master
    clone: 'no'
    update: 'no'
  register: cocoapods_specs_repo

- name: pod setup
  shell: bash -l -c "pod setup"
  when: cocoapods_specs_repo.before == None

- name: CocoaPods specs install with pod NOT FOR CI
  shell: bash -l -c "pod repo add master https://github.com/CocoaPods/Specs.git"
  when: >
    cocoapods_specs_repo.before == None and
    not lookup('env', 'IS_CI')

- name: Shallow checkout Cocoapds Specs repo FOR CI TEST
  git:
    repo: 'https://github.com/CocoaPods/Specs.git'
    dest: ~/.cocoapods/repos/master
    clone: 'yes'
    update: 'yes'
    depth: 1
  when: >
    cocoapods_specs_repo.before == None
    and lookup('env', 'IS_CI')

- name: "CocoaPods: pod repo update"
  shell: bash -l -c "pod repo update"
  when: not lookup('env', 'IS_CI')
