---
xclogparser_version: 0.2.22
xclogparser_url: https://github.com/MobileNativeFoundation/XCLogParser/releases/download/v{{ xclogparser_version }}/XCLogParser-macOS-{{ ansible_architecture }}-v{{ xclogparser_version }}.zip
xcbeautify_version: 0.9.1
xcbeautify_url: https://github.com/tuist/xcbeautify/releases/download/{{ xcbeautify_version }}/xcbeautify-{{ xcbeautify_version }}-{{ ansible_architecture }}-apple-macosx.zip
...
