export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"

# Homebrew
#  Don't do auto update
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

# Go
export PATH="$PATH:/usr/local/opt/go/libexec/bin"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
export GO111MODULE=auto

# Flutter & fvm
export PATH="$PATH:$HOME/.pub-cache/bin"
export PATH="$PATH:$HOME/fvm/default/bin"

# Ruby setup
if command -v asdf; then
  . $(brew --prefix asdf)/libexec/asdf.sh
fi

# Bitrise environments
if [ -s "$HOME/.profiles/bitrise_profile" ] ; then
  source "$HOME/.profiles/bitrise_profile"
fi

# (3rd party) Tools environments
if [ -s "$HOME/.profiles/tools_profile" ] ; then
  source "$HOME/.profiles/tools_profile"
fi

for PROFILE_SCRIPT in $( ls $HOME/profile.d/* ); do
  . $PROFILE_SCRIPT
done

if [ -f $HOME/profile.d/jenv.sh ]; then
  export JAVA_HOME="$(jenv prefix)"
fi

# Xamarin environments, if exists
if [ -s "$HOME/.profiles/xamarin_profile" ] ; then
  source "$HOME/.profiles/xamarin_profile"
fi

# keep a newline at the end of this file
