---
- name: Install curl
  package:
    name: curl
    state: present
    update_cache: true
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Check if brew is installed
  shell: "/opt/homebrew/bin/brew config"
  register: is_brew_installed
  changed_when: false
  ignore_errors: true

- name: Install brew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: is_brew_installed is failed

- name: Is brew in bash_profile
  shell: "grep brew ~/.bash_profile"
  changed_when: false
  ignore_errors: true
  register: bash_profile

- name: Setup brew
  shell: echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/vagrant/.zprofile

- name: Set brew 
  shell: eval "$(/opt/homebrew/bin/brew shellenv)"
