---
gem_packages:
  - name: "cocoapods"
  - name: "xcpretty"
  - name: "bundler"
  - name: "fastlane"
  - name: "xcov"
  - name: "jazzy"
  - name: "xcpretty-json-formatter"
  - name: "trainer"
  - name: "slather"
