---
- name: brew install node
  homebrew:
    name: node@12
    state: present
    update_homebrew: true

- name: Check if node already linked to node@12
  shell: "node --version"
  register: node_version
  changed_when: false
  ignore_errors: true

- name: brew link node@12
  shell: bash -l -c "brew link --overwrite --force node@12"
  when: not node_version.stdout.startswith('v12')

- name: Install NPM packages
  npm:
    name: "{{ item.name }}"
    global: true
    version: "{{ item.version }}"
  with_items:
    - "{{ npm_packages }}"
