---
- name: brew install node
  homebrew:
    name: node@16
    state: present
    update_homebrew: true

- name: Check if node already linked to node@16
  shell: "node --version"
  register: node_version
  changed_when: false
  ignore_errors: true

- name: brew link node@16
  command: brew link --overwrite --force node@16
  environment:
    PATH: /usr/local/bin/:{{ ansible_env.PATH }}
  when: not node_version.stdout.startswith('v16')

- name: Install NPM packages
  npm:
    name: "{{ item.name }}"
    global: true
    version: "{{ item.version }}"
  with_items:
    - "{{ npm_packages }}"
