---
- name: create profile directories
  ansible.builtin.file:
    path: "$HOME/{{ item.path }}"
    state: directory
    owner: "{{ param_user }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ directories }}"

- name: install profiles
  ansible.builtin.copy:
    src: "{{ item.name }}"
    dest: "$HOME/{{ item.dest }}"
    owner: "{{ param_user }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ profiles }}"
