---
# kcpassword from https://github.com/veertuinc/kcpassword.git
- name: kcpassword python file
  copy:
    src: kcpassword
    dest: /usr/local/bin/kcpassword
    owner: "{{ param_user }}"
    group: staff
    mode: '0700'

- name: run kcpassword
  become: true
  command: /opt/homebrew/bin/python3 /usr/local/bin/kcpassword "{{ password_of_param_user }}"

- name: add "{{ param_user }}" to defaults autologin
  become: true
  command: /usr/bin/defaults write /Library/Preferences/com.apple.loginwindow autoLoginUser "{{ param_user }}"

- name: Fail if kcpasswd fails
  become: true
  shell: "ls -al /etc/kcpassword"
