---
gem_packages:
  - name: "xcpretty-json-formatter"
    version: "0.1.1"
  - name: "trainer"
    version: "0.9.1"
  - name: "slather"
    version: "2.5.0"
brew_packages:
  - name: "jq"
  - name: "screen"
  - name: "applesimutils"
  - name: "openconnect"
  - name: "awscli"
  - name: "cmake"
  - name: "gpg"

danger_swift_unsupported_versions:
  - '10.3'
  - '11.1'
  - '11.3'
...
