---
- name: Test if {{ ruby.version }} is installed
  shell: "{{ brew_path }}/asdf list ruby | grep {{ ruby.version }}"
  register: ruby_version_is_installed
  changed_when: false
  ignore_errors: true

- name: Install ruby {{ ruby.version }}
  shell: "{{ brew_path }}/asdf install ruby {{ ruby.version }}"
  when: ruby_version_is_installed.rc != 0
  retries: 3
...
