---
# XCLogParser
- name: Check if Xclogparser is present
  shell: bash -l -c "xclogparser version | awk '{print $2}'"
  register: xclogparser
  ignore_errors: true
  no_log: true

- name: "Download Xclogparser {{ xclogparser_version }}"
  get_url:
    url: "{{ xclogparser_url }}"
    dest: /tmp/xclogparser.zip
  when: xclogparser.rc != 0 or xclogparser.stdout != xclogparser_version

- name: Unarchive xclogparser binary
  unarchive:
    src: /tmp/xclogparser.zip
    dest: "{{ '/opt/homebrew/bin/' if ansible_architecture == 'arm64' else '/usr/local/bin/' }}"
    owner: "{{ param_user }}"
    mode: "0755"
    remote_src: true
  become: true
  when: xclogparser.rc != 0 or xclogparser.stdout != xclogparser_version

# XCBeautify
- name: Check if XCBeautify is present
  shell:  bash -l -c "xcbeautify --version | awk '{print $2}'"
  register: xcbeautify
  ignore_errors: true
  no_log: true

- name: "Download XCBeautify {{ xcbeautify_version }}"
  get_url:
    url: "{{ xcbeautify_url }}"
    dest: /tmp/xcbeautify.zip
  when: xcbeautify.rc != 0 or xcbeautify.stdout != xcbeautify_version

- name: Unarchive XCBeautify binary
  unarchive:
    src: /tmp/xcbeautify.zip
    dest: "{{ '/opt/homebrew/bin/' if ansible_architecture == 'arm64' else '/usr/local/bin/' }}"
    owner: "{{ param_user }}"
    mode: "0755"
    remote_src: true
  become: true
  when: xcbeautify.rc != 0 or xcbeautify.stdout != xcbeautify_version
...
